### ISSUE TITLE
Transferir gerenciamento de chaves

### ISSUE THREAD

**Issue by maiconandsilva** [maiconandsilva/LGPD-compliant-website#1]
Atualmente as chaves dos Customer pseudonimizados são guardadas em um arquivo no formato _id;chave_ (olhar arquivo [isolated_db_keys.txt](https://github.com/maiconandsilva/LGPD-compliant-website/files/5502146/isolated_db_keys.txt) em anexo como exemplo).

É necessário utilizar uma forma externa de gerenciar estas chaves.

A princípio a ideia é utilizar um serviço, como o [KMS](https://aws.amazon.com/pt/kms), ou um banco de dados).

Alterar método [store_key_id](https://github.com/maiconandsilva/LGPD-compliant-website/blob/a7b56b030590d8238e836dae7511860915e805cb/views/account.py#L59).

**Comment by maiconandsilva** [comment]
@Andrerodrigues0018, vou atribuir essa tarefa para você. Se houver alguma dúvida ou quiser trocar, pode notificar por aqui.

**Comment by maiconandsilva** [comment]
### Gerenciamento de chaves feito com Azure

![Screenshot (59)](https://user-images.githubusercontent.com/64911189/100160952-4ce1ce80-2e8f-11eb-8ec8-e9a7c505d44f.png)
![Screenshot (56)](https://user-images.githubusercontent.com/64911189/100160956-4e12fb80-2e8f-11eb-9250-4ef476e37ea8.png)
![Screenshot (58)](https://user-images.githubusercontent.com/64911189/100160957-4eab9200-2e8f-11eb-89c7-c474c274e096.png)

**Comment by rodrigoqfcosta** [comment]
Boa noite Maicon, tudo bem?

Tentei progredir com AWS da Amazon sem sucessos,  creio que com Azure
conseguirei fazer alguma coisa.👍🏾

Em sex, 6 de nov de 2020 15:23, Maicon Mauricio <notifications@github.com>
escreveu:
