### ISSUE TITLE
DOCUMENTAÇÃO/WIKI/README (Revisão)

### ISSUE THREAD

**Issue by maiconandsilva** [maiconandsilva/LGPD-compliant-website#5]
Na documentação do projeto deve conter:

- [x] Sumário (similar ao print que eu mandei abaixo)
- [x] Problema (que o projeto se proprõe a solucionar)
- [x] Solução (descricao das soluções encontradas para o problema)
- [x] Adicionar explicação ao Burndown velocity chart (como são divididas as reuniões etc)
- [x] Arquitetura do sistema
- [x] GIFs e prints das telas do site
- [x] Link para a demonstração do projeto no Heroku
- [x] Rotas do site e métodos HTTP usados
- [x] Explicação criptografia
- [x] sprints já feitas em forma de checklist (com explicação do valor principal da entrega)
- [x] Link para as sprints (milestones do github)
- [x] Tecnologias usadas
- [x] Instalação e execução
- [x] Configuração de desenvolvimento
- [x] Configuração dos serviços de banco de dados
- [x] Integrantes do projeto

Links úteis:
- [WIKI](https://github.com/maiconandsilva/LGPD-compliant-website/wiki)
- [README](https://github.com/maiconandsilva/LGPD-compliant-website/blob/main/README.md)

**Comment by maiconandsilva** [comment]
@Andrerodrigues0018, aceitar solicitação to Github para eu atribuir essa tarefa para você.

Você pode listar todas as tarefas que serão realizadas por aqui. Depois pode criar um issue para cada tarefa e atribuir para uma pessoa.

**Comment by maiconandsilva** [comment]
Achei legal da forma que eles fizeram

![Integrantes do grupo - exemplo](https://user-images.githubusercontent.com/64911189/98446670-da869580-20fd-11eb-9f53-16e5517d7ed3.png)
![Sumário - exemplo](https://user-images.githubusercontent.com/64911189/98446673-db1f2c00-20fd-11eb-8990-d8b0b0d05aa3.png)

**Comment by maiconandsilva** [comment]
## Algumas Informações do projeto

- [Kanban a partir da 5º sprint](https://github.com/maiconandsilva/LGPD-compliant-website/projects/1?fullscreen=true)
- [Tarefas abertas 5º sprint](https://github.com/maiconandsilva/LGPD-compliant-website/milestone/1)
- [Tarefas fechadas 5º sprint](https://github.com/maiconandsilva/LGPD-compliant-website/milestone/1?closed=1)
- [Tarefas abertas 6º sprint](https://github.com/maiconandsilva/LGPD-compliant-website/milestone/2)
- [Tarefas fechadas 6º sprint](https://github.com/maiconandsilva/LGPD-compliant-website/milestone/2?closed=1)

**Principais bibliotecas Python:**

> cryptography==3.2.1
> Flask==1.1.2
> Flask-SQLAlchemy==2.4.4
> Flask-WTF==0.14.3
> Jinja2==2.11.2
> SQLAlchemy==1.3.19
> SQLAlchemy-Utils==0.36.8
> WTForms-Alchemy==0.17.0

**Framework CSS: [UIkit 3.5.9](https://github.com/uikit/uikit/releases/tag/v3.5.9)**

**Pseudonimização do cliente/usuário:**

- Biblioteca Python usada para criptografia: [cryptography](https://cryptography.io/en/3.2.1/)
- Algoritmo de criptografia simétrica usado: [Fernet](https://cryptography.io/en/3.2.1/fernet/) ([link da especificação](https://github.com/fernet/spec/blob/master/Spec.md));
- Para cada usuário é gerada uma chave aleatória de 256 bits que é guardada externamente junto ao id do usuário;
- Se possível, colocar explicação resumida no documento.

**Scripts SQL carregados pelo Docker: [dellstore.sql](https://gist.githubusercontent.com/maiconandsilva/a12d990d3ff7f3f966eb325015ef7550/raw/3f6bda85a35161bd881725bf29411965f8187803/dellstore.sql) e [customer_personal_info.sql](https://gist.githubusercontent.com/maiconandsilva/ef9e67bfebcb24a8b5bfe16d5c89d3ba/raw/customer_personal_info.sql)**

**Comment by maurosakugawa** [comment]
@maiconandsilva e @Andrerodrigues0018, quanto ao sumário, será que não seria melhor algo do tipo 'table of contents', como no exemplo abaixo?
![Table-of-contents](https://user-images.githubusercontent.com/43210185/98489982-e4e48480-220e-11eb-8e91-eb5cc0161b17.png)
É assim que faço em meus repositórios, mas esse readme foi gerado pelo React-js. O Repositório onde está o readme é esse: https://github.com/maurosakugawa/Api-React-HTTP-fetch
