### ISSUE TITLE
Melhorar telas frontend já existentes

### ISSUE THREAD

**Issue by maiconandsilva** [maiconandsilva/LGPD-compliant-website#6]
A alteração será feita nos [templates](https://github.com/maiconandsilva/LGPD-compliant-website/tree/main/templates) das [rotas](https://github.com/maiconandsilva/LGPD-compliant-website/blob/main/server.py):

- [x] /signup (registrar).
- [x] /signin (entrar na conta)
- [x] /account (visualização de dados do cliente)
  - [x] Adicionar botão de signout no front chamando a rota já existente /account/signout
  - [x] Adicionar abas à esquerda da página
  - [x] Adicionar modal de confirmação para deletar a conta (você poderia usar javascript e capturar o event submit do botão delete)

Os templates têm o mesmo nome das rotas.

**Comment by maiconandsilva** [comment]
@c0sta, aceitar solicitação do Github para eu poder atribuir a tarefa para você.

**Comment by c0sta** [comment]
Aceitei lá! Mals a demora não tinha visto a notificação

**Comment by maiconandsilva** [comment]
#### Aqui tem os exemplos da página de login e registro (a partir da página do Facebook) que conversamos na reunião.

![exemplo sign up](https://user-images.githubusercontent.com/64911189/98448070-600f4300-2108-11eb-92cd-11cafae668a3.png)
![exemplo sign in)](https://user-images.githubusercontent.com/64911189/98448071-61407000-2108-11eb-846a-0efe64ce7983.png)

Como no exemplo: uma barra em cima com um icone à esquerda em cada uma das telas.

A página /account fica a seu critério (como já foi conversado).

**Comment by maiconandsilva** [comment]
@c0sta, se puder fazer a tela **conta** com abas à esquerda daquele card como tinhamos conversado. Vou adicionar no card.

Link do print: https://getuikit.com/docs/nav#default-modifier

As abas seriam:
 - Account
 - Address
 - Payment

![Screenshot (65)](https://user-images.githubusercontent.com/64911189/100513905-5c8f3a80-314f-11eb-9c42-2e5759b338fb.png)

As outras ficaram 💯
